name: config of answer generation for arena-hard-v0.1

bench_name: arena-hard-v0.1

temperature: 0.0
max_tokens: 4096
num_choices: 1

# a list of model to generate answers
model_list:
#  - krikri-annealing-dpo-max-length-norm-dpo-fixes-length-norm-round-3-with-IF-final-checkpoint
  - krikri-annealing-dpo-max-length-norm-dpo-fixes-length-norm-round-3-with-IF-checkpoint-2316

#  - krikri-annealing-dpo-max-length-norm-dpo-fixes-length-norm-round-2 # DONE
#  - krikri-annealing-dpo-max-length-norm-dpo-fixes-length-norm-round-1-low-lr # DONE
#  - krikri-annealing-sft-stage2-merge-dpo-max-length-norm-dpo-fixes-length-norm_0.4-dpo_min_0.3dpo_max-length-norm-fixes_on_policy-checkpoint-1560_0.3-dare_tie # DONE
#  - krikri-annealing-sft-stage2-merge-dpo-max-length-norm-dpo-fixes-length-norm_0.45-dpo_min_0.55-dare_tie # DONE
# - krikri-annealing-sft-stage2-merge-dpo-max-length-norm-dpo-fixes-length-norm_0.55-dpo_min_0.45-dare_tie # DONE
 
# - krikri-annealing-sft-stage2-dpo_max-length-norm-dpo-fixes_off_policy-length-norm # DONE
# - krikri-annealing-sft-stage2-dpo_max-length-norm-dpo-fixes-length-norm # DONE 
# - krikri-annealing-sft-stage2-dpo_max-length-norm-fixes_on_policy-checkpoint-1560 # DONE

#  - aya-expanse-8b # DONE
#  - aya-expanse-32b # DONE
#  - krikri-annealing-sft-stage2-run4 # DONE
#  - krikri-annealing-sft-stage2-dpo_max-length-norm-run4 # DONE
#  - krikri-annealing-sft-stage2-dpo_max-length-norm-fixes_on_policy # DONE
