name: config of answer generation for arena-hard-v0.1

bench_name: arena-hard-v0.1

temperature: 0.0
max_tokens: 4096
num_choices: 1

# a list of model to generate answers
model_list:
  - aya-expanse-32b
  # - krikri-annealing-sft-stage2-dpo_max-length-norm-run4
  # - krikri-annealing-sft-stage2-dpo_max-length-norm-fixes_on_policy
  # - krikri-annealing-sft-stage2-dpo_max-length-norm-fixes_on_policy-checkpoint-1560
  # - krikri-annealing-sft-stage2-run4
  # - aya-expanse-8b
